openapi: 3.0.3
info:
  title: User Service
  version: 1.0.0
paths:
  /users/{id}:
    get:
      summary: Получить пользователя по ID
      operationId: getUserById          # <-- Это имя превратится в метод на Go!
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer               # <-- ogen сам поймет, что это число
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        email:
          type: string                  # <-- Необязательное поле

